comment:
  image:
    repository: maks123/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: maks123/post
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: maks123
    tag: latest
    service:
      externalPort: 9292

