global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#maxim_serenkov'

